### ISSUE TITLE
Dateitypen werden nicht anerkannt

### ISSUE THREAD

**Issue by fietstouring** [KLXM/filepond_uploader#13]
bei mir funktioniert zb `image/*,application/pdf,.pdf`
hingegen mit` image/jpg,.jpg,application/pdf,.pdf` funktioniert `jpg` nicht mehr 

dann zb .docx funktioniert gar nicht
allerdings mit `application/vnd.openxmlformats-officedocument.wordprocessingml.document,.docx` funktioniert docx. 

will ich nur jpg und pdf zulassen schaffe ich das nicht
`image/jpg,.jpg,application/pdf,.pdf` wird jpg nicht akzeptiert

**Comment by skerbis** [comment]
`image/jpg,application/pdf`
versuch mal ... ich glaube ,.pdf, ,.jpg oder so wird nicht richtig interpretiert und sollte rausgelassen werden.

**Comment by skerbis** [comment]
https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1734984242501509
